#!/usr/bin/env node
/**
 * Vendors htmx's ESM build verbatim (spec C.4.3).
 *
 * Upstream htmx 2.0.10 ships `dist/htmx.esm.js` (unminified ESM, ~169 KB) and
 * `dist/htmx.min.js` (minified UMD). It ships NO minified ESM build, so the
 * name `htmx.esm.min.js` used in spec v1.1 does not exist upstream. We vendor
 * the real file under its real name rather than shipping a filename that lies
 * about its contents. See spec-v1.2.md for the amendment.
 *
 * The version banner makes a deployed site identifiable. The file is only
 * rewritten when its content actually changes, which keeps builds byte-stable
 * and `git status` quiet.
 */
import { createHash } from 'node:crypto'
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const htmxDir = join(root, 'node_modules', 'htmx.org')
const src = join(htmxDir, 'dist', 'htmx.esm.js')
const outDir = join(root, 'vendor')
const out = join(outDir, 'htmx.esm.js')

if (!existsSync(src)) {
  console.error(`[vendor] htmx not found at ${src}`)
  console.error('[vendor] install it with: npm install -D --save-exact htmx.org@2.0.10')
  process.exit(1)
}

const pkg = JSON.parse(readFileSync(join(htmxDir, 'package.json'), 'utf8'))
const body = readFileSync(src, 'utf8')

// The runtime does `import htmx from './htmx.esm.js'`. If upstream ever drops
// the default export, fail here rather than in a reader's browser.
if (!/\bexport\s+default\b/.test(body)) {
  console.error('[vendor] htmx.esm.js has no default export; the runtime import would break.')
  process.exit(1)
}

const banner = [
  `/*! htmx ${pkg.version} (ESM) - vendored verbatim by scripts/vendor-htmx.mjs`,
  ` *  license: ${pkg.license ?? 'see htmx.LICENSE'} - https://htmx.org/`,
  ' *  Do not edit this file. Regenerate with `npm run vendor`.',
  ' */',
  '',
].join('\n')

const next = banner + body
const prev = existsSync(out) ? readFileSync(out, 'utf8') : null

if (prev === next) {
  console.log(`[vendor] vendor/htmx.esm.js already current (htmx ${pkg.version}, ${digest(next)}).`)
} else {
  mkdirSync(outDir, { recursive: true })
  writeFileSync(out, next)
  console.log(
    `[vendor] wrote vendor/htmx.esm.js (htmx ${pkg.version}, ${next.length} bytes, ${digest(next)}).`,
  )
}

const licenseSrc = join(htmxDir, 'LICENSE')
if (existsSync(licenseSrc)) copyFileSync(licenseSrc, join(outDir, 'htmx.LICENSE'))

function digest(text) {
  return createHash('sha256').update(text).digest('hex').slice(0, 12)
}
